package racoonsoft.tinyheroes.enums;

public enum BuildingTypes
{
    CASTLE,
    FORGE,
    MAGE_TOWER,

    WARRIOR_HOUSE,
    WARRIOR_PALADIN_HOUSE,
    WARRIOR_DARKSIR_HOUSE,
    WARRIOR_BARBARIAN_HOUSE,

    ARCHER_HOUSE,
    ARCHER_ARBALESTER_HOUSE,
    ARCHER_SNIPER_HOUSE,
    ARCHER_OF_SHIWA_HOUSE,

    MAGE_HOUSE,
    MAGE_FIRE_HOUSE,
    MAGE_WATER_HOUSE,
    MAGE_EARTH_HOUSE,
    MAGE_AIR_HOUSE,
    MAGE_NECROMANCER_HOUSE,

    MONK_HOUSE,
    MONK_KUNGFU_HOUSE,
    MONK_SOLID_HOUSE,
    MONK_ETHEREAL_HOUSE
}
